# Generated by Django 2.2.1 on 2019-05-20 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movierec', '0002_user_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='zip_code',
        ),
    ]
