# Generated by Django 2.2.1 on 2019-05-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movierec', '0003_remove_user_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
