# Generated by Django 2.2.1 on 2019-05-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movierec', '0004_user_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zip_code',
            field=models.CharField(max_length=100),
        ),
    ]
